version: "3"
services:
  playerservice:
    image: ghcr.io/bloomgamestudio/playerservice:main
    volumes:
      - playerservice:/database
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "1323:1323"
    restart: unless-stopped

volumes:
  playerservice: