openapi: 3.0.0
info:
  title: PlayerService
  version: 1.0.0
servers:
  - url: http://127.0.0.1:1323
paths:
  /ping:
    get:
      tags:
        - default
      summary: Ping
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /player:
    post:
      tags:
        - default
      summary: CreatePlayer
      description: Create Player
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                UserID: 00000000-0000-0000-0000-000000000000
                Name: User3
                Layer: layer1
                Position:
                  x: 1
                  'y': 2
                  z: 3
                Rotation:
                  x: 4
                  'y': 5
                  z: 6
                Scale:
                  x: 7
                  'y': 8
                  z: 9
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
