name: Publish to pkg.go.dev

on:
  push:
    branches:
      - main
      - staging
      - dev

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Fetch tags
      run: git fetch --tags

    - name: Build and publish to pkg.go.dev
      run: |
        go install github.com/goreleaser/goreleaser@v0.180.0
        GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} goreleaser release --rm-dist --snapshot --release-notes <(echo "Release for tag v1.0.0")
